import { GamepadDirectional } from "lucide-react";

export const CONTACT_URL = 'https://wa.me/message/CXY6GG6AUHNRE1';

export const CATEGORIES = [
  { id: 'motion', label: 'Motion design' },
  { id: 'product', label: 'Product design' },
];

export const profile = {
  name: "Maya's Archive",
  shortName: 'Maya',
  location: 'Glasgow, UK',
  bio: "I'm a solo designer making expressive motion and thoughtful products, with the goal to add my own piece of creativity to the digital world.",
  roles: ['Product designer', 'Motion designer'],
  links: [
    { label: 'Instagram', href: 'https://www.instagram.com/mayasarchive.zip/', icon: 'instagram' },
    { label: 'TikTok', href: 'https://www.tiktok.com/@mayasarchive.zip', icon: 'tiktok' },
    { label: 'threads', href: 'https://www.threads.com/@mayasarchive.zip', icon: 'threads' },
  ],
};

export const projects = [
  {
    id: 'sourcd',
    slug: 'sourcd',
    title: 'sourcd.',
    kicker: 'Product design/Software development',
    category: 'product',
    description: '',
    summary: 'Platform for creatives to save inspiration from any where onlines. Sourcd is still on development so the github is not available to the public',
    thumbnail: '/assets/sourcd-thumbnail.png',
    media: ['/assets/sourcd-case-study.png'],
    tools: ['affinity, next.js'],
    skills: ['ui design,product design, front-end development'],
    featured: false,
    tone: 'lavender',
    year: '2026',
  },
  {
    id: 'Ikea-ad',
    slug: 'Ikea-ad',
    title: 'Ikea Ad',
    kicker: 'Case study',
    category: 'motion',
    description: '',
    summary: 'concept ad i made for Ikea. short social media ad showcasing motion animations and how ikea helps make your home ideas real.',
    thumbnail: '/assets/Ikea_Ad.mp4',
    media: ['/assets/Ikea_Ad.mp4'],
    tools: ['After Effects, affinity'],
    skills: ['Motion design'],
    featured: false,
    tone: 'lavender',
    year: '2026',
  },
  {
    id: 'Quimera',
    slug: 'Quimera',
    title: 'Quimera',
    kicker: 'Brand Assets',
    category: 'motion',
    description: '',
    summary: 'Logo animations i made for the brand identity of quimera',
    thumbnail: '/assets/Quimera_Animation_2.mp4',
    media: ['/assets/Quimera_Animation_1.mp4', '/assets/Quimera_Animation_2.mp4', '/assets/Quimera_Animation_3.mp4'],
    tools: ['After Effects, affinity'],
    skills: ['Motion design, Logo animation'],
    featured: false,
    tone: 'lavender',
    year: '2026',
  },
  {
    id: 'causal',
    slug: 'causal',
    title: 'causal ad',
    kicker: 'social media ad',
    category: 'motion',
    description: '',
    summary: 'Social media ad i made, for causal. An infinite workspace for your ideas.',
    thumbnail: '/assets/causal_ad.mp4',
    media: ['/assets/causal_ad.mp4'],
    tools: ['After Effects, affinity,'],
    skills: ['Motion design'],
    externalUrl: 'https://www.instagram.com/p/Dct4uJqSMLO/',
    featured: true,
    tone: 'lavender',
    year: '2026',
  },
  {
    id: 'google m3e',
    slug: 'google-m3e-ad',
    title: 'Google material 3 expressive',
    kicker: 'case study',
    category: 'motion',
    description: '',
    summary: 'kinetic motion design ad i made for google material 3 expressive, showcasing their ui elements - concept work',
    thumbnail: '/assets/google-m3e-ad.mp4',
    media: ['/assets/google-m3e-ad.mp4'],
    tools: ['aftereffects, affinity'],
    skills: ['motion design'],
    featured: true,
    tone: 'lavender',
    year: '2026',
  },
    {
    id: 'edithub',
    slug: 'edithub',
    title: 'edithub',
    kicker: 'Product design/Software development',
    category: 'product',
    description: '',
    summary: 'realised a lot of editors want a marketplace to get scenepacks and editing assets so i made one. Concept work.',
    thumbnail: '/assets/edithub-thumbnail.png',
    media: ['/assets/edithub-case-study.png'],
    tools: ['next.js, css'],
    skills: ['web design, product design'],
    externalUrl: 'https://github.com/edithub-app/edithub-app',
    featured: false,
    tone: 'lavender',
    year: '2026',
  },

  {
    id: '6ixstudio',
    slug: '6ixstudio',
    title: '6ixstudio showreel',
    kicker: 'motion design',
    category: 'motion',
    description: '',
    summary: 'Showreel for 6ixstudio - A creative studio based in italy',
    thumbnail: '/assets/6Ixstudio.mp4',
    media: ['/assets/6Ixstudio.mp4'],
    tools: ['aftereffects, affinity'],
    skills: ['motion design'],
    featured: false,
    tone: 'lavender',
    year: '2026',
  },
  /*{
    id: 'THE',
    slug: 'theditingco',
    title: 'theditingco',
    kicker: 'web design',
    category: 'product',
    description: '',
    summary: 'Portfolio/website designed for theditingco',
    thumbnail: '/assets/THE-thumbnail.png',
    media: ['/assets/the-full-breakdown.png'],
    tools: ['framer, next.js, css'],
    skills: ['web design'],
    externalUrl: 'https://theditingcompany.vercel.app/',
    featured: false,
    tone: 'lavender',
  },*/
];

export const featuredProject = projects.find((project) => project.featured) ?? projects[0];
